chat:
  gpt:
    config:
      okhttp:
        proxy:
          host: 127.0.0.1
          port: 7890
        interceptors:
          - com.disaster.chatgpt.infrastructure.client.interceptor.OpenAiResponseInterceptor
          - com.disaster.chatgpt.infrastructure.client.interceptor.DefaultOpenAiAuthInterceptor
      type: DEFAULT
      apikey:
        - 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
      strategy: com.disaster.chatgpt.infrastructure.client.function.KeyRandomStrategy
      interceptor: com.disaster.chatgpt.infrastructure.client.interceptor.DynamicKeyOpenAiAuthInterceptor

spring:
  application:
    name: chat-gpt-wechat
